### ISSUE TITLE
Can't create the player

### ISSUE THREAD

**Issue by laminsk** [danbrough/andrudio#4]
Hi there

Just trying out the updated code and I'm running into the problem. Here's the log output.

09-03 13:18:32.716  27169-27169/? I/danbroid.andrudio﹕ ap_create()
09-03 13:18:32.716  27169-27169/? E/danbroid.andrudio﹕ pipe failed
09-03 13:18:32.716  27169-27169/? V/danbroid.andrudio﹕ ap_send_cmd::CMD_EXIT
09-03 13:18:32.716  27169-27169/? I/danbroid.andrudio﹕ ap_delete::calling join on 0
09-03 13:18:32.716  27169-27169/? I/danbroid.andrudio﹕ ap_delete::done
09-03 13:18:32.726  27169-27169/? E/danbroid.andrudio﹕ failed to create playe

If I'm not mistaken, it's caused by:

if (pipe2(player->pipe, O_NONBLOCK) != 0) { .. }

Thanks

**Comment by danbrough** [comment]
Howdy,
How are you testing this?

**Comment by laminsk** [comment]
Hi 

Thanks for the reply. I'm getting this error when trying to build using ndk-build.

audioplayer.c:183: error: undefined reference to 'pipe2'
collect2: error: ld returned 1 exit status

Commenting out the if statement works fine without any error.

Any ideas please?

Thanks

**Comment by danbrough** [comment]
What version of the ndk are you using?

**Comment by danbrough** [comment]
I'm confused as you mention a problem with a runtime error but also a problem with a compile time error.
I assume that the runtime error is with the demo apk and the you can't compile the code because of the compile error.
Are you compiling on linux ? 
Are you using the latest NDK ?

**Comment by laminsk** [comment]
Apologies for late reply and thank you very much for providing the
pointers. I'm compiling on Mac and using old NDK.

It seems odd that after changing to latest NDK as you have suggested, I do
not get that error message any more!

One more question please if you don't mind.

I'm in the process of passing on custom http header to ffmpeg using
AVDictionary like this. However it doesn't seem to work at all, but it
might be that I'm not utilising it correctly?

Many Thanks

AVDictionary *options = NULL;
av_dict_set(&options, "headers", "User-Agent: custom agent header
here;\r\nReferer:
http://www.mywebsite.com/", 0);

avformat_open_input(&player->ic, player->url, NULL,& options);

**Comment by laminsk** [comment]
No worries, I got it working now :+1: 

Here's the correct format.

av_dict_set(&options, "user-agent", "Firefox", 0);

Cheers

**Comment by danbrough** [comment]
I guess pipe2 wasn't in the older header files. I could use regular pipe but it seems to work fine in the emulators so I assume its ok.
