### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed

### ISSUE THREAD

**Issue by danbrough** [danbrough/andrudio#5]
`java.lang.UnsatisfiedLinkError: dlopen failed: cannot find "libavutil.so" from verneed[0] in DT_NEEDED list for "/data/app/danbroid.andrudio.demo-1/lib/x86/libavresample.so"`

This is on an Android6.0 Atom x86 emulator.
The Google Api's emulator for Atom x86 works fine.
Haven't come across this on any actual devices.
Seems to be an issue loading the prebuilt ffmpeg binaries.

**Comment by adelinolobao** [comment]
Hi,
FFmpeg usese texts relocations and from what it looks like in this commit
https://android-review.googlesource.com/#/c/155950/1/linker/linker.cpp

That is not allow anymore in Android M, will have problems to run ffmpeg.

**Comment by adelinolobao** [comment]
Hi guys, 

To fix this problem please vote in this bug report
https://code.google.com/p/android/issues/detail?id=191235

Thanks

**Comment by danbrough** [comment]
This should be fixed now. I've added sonames to the ffmpeg libraries and also add --disable-asm for the x86 version to fix the text relocations issue. I've tested it on arm,x86 and x86_64. Seems to be working well. The google play demo is updated also.
